version: '2'

volumes:
  postgres-data:
    driver: local
services:
  # Postgres (9.5)
  postgres:
    image: ambientum/postgres:9.6
    container_name: onde_tem_postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=onde_tem_repo
